class DataCityCar {
  List<String> city = [
    "Агрыз",
    "Азнакаево",
    "Альметьевск",
    "Бавлы",
    "Болгары",
    "Бугульма",
    "Буинск",
    "Елабуга",
    "Заинск",
    "Зеленодольск",
    "Казань",
    "Лениногорск",
    "Мамадыш",
    "Менделеевск",
    "Мензелинск",
    "Набережные Челны",
    "Нижнекамск",
    "Нурлат",
    "Тетюши",
    "Чистополь"
  ];
  List<String> car = [
    "Audi",
    "BMW",
    "Ford",
    "Honda",
    "Hyndai",
    "Kia",
    "Lada",
    "Mazda",
    "Mercedes-Benz",
    "Mitsubishi",
    "Nissan",
    "Renault",
    "Skoda",
    "Toyota",
    "Volkswagen",
    "Acura",
    "Daihatsu",
    "Datsun",
    "Infiniti",
    "Isuzu",
    "Lexus",
    "Scion",
    "Subaru",
    "Suzuki",
    "Chevrolet",
    "Jeep",
    "ГАЗ",
    "Москвич",
    "УАЗ",
    "Pegout"
  ];
  List<String> enginePower = ["0-100", "101-199", "200+"];
}
